<!-- jQuery 2.2.0 -->
<script src="<?=\core\core::ROOT_APP?>plugins/jquery/jQuery-2.2.0.min.js"></script>
<!-- AdminLTE App -->
<script src="<?=\core\core::ROOT_APP?>site_design/js/app.min.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/jquery/jQuery-ui.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="<?=\core\core::ROOT_APP?>plugins/bootstrap/js/bootstrap.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/bootstrap/js/bootbox.min.js"></script>

<script src="<?=\core\core::ROOT_APP?>plugins/timepicker/bootstrap-timepicker.min.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/colorpicker/bootstrap-colorpicker.min.js"></script>

<script src="<?=\core\core::ROOT_APP?>plugins/select2/select2.full.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slimScroll/jquery.slimscroll.min.js"></script>

<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/lib/jquery-1.7.min.js"></script>

<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/lib/jquery.event.drag-2.2.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.core.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.groupitemmetadataprovider.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.formatters.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.grid.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.dataview.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.editors.js"></script>



<script src="<?=\core\core::ROOT_APP?>plugins/highcharts-4.1.5/js/highcharts.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/highcharts-4.1.5/js/modules/exporting.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/highcharts-4.1.5/js/highcharts-3d.js"></script>

<!-- iKroAnimate -->

<script src="<?=\core\core::ROOT_APP?>plugins/pnotify/pnotify.custom.min.js"></script>
<script src="<?=\core\core::ROOT_APP?>plugins/iCheck/icheck.min.js"></script>

<script src="<?=\core\core::ROOT_APP?>site_design/js/iKroAnimate.js"></script>
<script src="<?=\core\core::ROOT_APP?>site_design/js/jsGeneral.js"></script>
