<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="bg-danger"><a class="bg-red" href="#" data-toggle="control-sidebar"><i class="fa fa-close text-white"></i></a></li>
        <li ><a id="mnu_tab_01" href="#mnu_tab_box_01" data-toggle="tab"><i class="fa fa-envelope"></i></a></li>
        <li ><a id="mnu_tab_02" href="#mnu_tab_box_02" data-toggle="tab"><i class="fa fa-bell"></i></a></li>
        <li ><a id="mnu_tab_03" href="#mnu_tab_box_03" data-toggle="tab"><i class="fa fa-flag"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="mnu_tab_box_01">

            <h3 class="control-sidebar-heading">Contactos</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0);" onclick="fnsdMenu(18)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Alejandro Gomez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="fnsdMenu(18)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Alejandro Gomez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Enrique Chavez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="fnsdMenu(18)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Alejandro Gomez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Enrique Chavez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" onclick="fnsdMenu(18)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Alejandro Gomez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Enrique Chavez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Enrique Chavez</h4>

                            <p>Sistemas</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <div class="tab-pane" id="mnu_tab_box_02">
            <h3 class="control-sidebar-heading">Alertas</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Creaci&oacute;n de Menu
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>

        <div class="tab-pane" id="mnu_tab_box_03">
            <h3 class="control-sidebar-heading"> Tareas</h3>

        </div>

        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->