<?php
/**
 * Created by PhpStorm.
 * User: alejandro.gomez
 * Date: 30/01/2017
 * Time: 05:44 PM
 */
?>
<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Last-Modified" content="0">
<meta http-equiv="expires" content="0">
<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
<meta http-equiv="Pragma" content="no-cache">

<title><?=\core\core::NAME_APP?></title>
<link rel="shortcut icon" href="<?=\core\core::ROOT_APP?>site_design/img/icons/favicon.ico" type="image/x-icon" />
<link rel="icon" href="<?=\core\core::ROOT_APP?>site_design/img/icons/favicon.ico" type="image/x-icon" />
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.5 -->
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/bootstrap/css/bootstrap.css">
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/timepicker/bootstrap-timepicker.min.css">

<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/colorpicker/bootstrap-colorpicker.css">

<!-- Font Awesome -->
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/fonts/font-awesome/css/font-awesome.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/select2/select2.css">
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/slickgrid/slick.grid.css"  type="text/css"/>
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>site_design/css/cssSlickGrid.css" type="text/css"/>
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/pnotify/pnotify.custom.min.css">
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>plugins/iCheck/flat/blue.css">

<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>site_design/css/SistemaIntegral.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="<?=\core\core::ROOT_APP?>site_design/css/skins/_all-skins.css">
<!--[endif]-->
